### ISSUE TITLE
Silence at the start of recordings (WASAPI and ASIO)

### ISSUE THREAD

**Issue by mathiassmichno** [spatialaudio/python-sounddevice#44] opened 2016-09-28 14:05 UTC
Hi,
I am encountering an issue where all my recordings start with silence.
When I record with a WASAPI device the silence usually lasts 255 samples whereas ASIO device recordings starts with 512 samples of silence i.e. the value 0

I use the following small snippet to record the audio.

```
import sounddevice as sd
from scipy.io import wavfile
import numpy as np
import begin

@begin.start(auto_convert=True)
def main(sound_device: 'Sound Device Name' = 'DMX 6Fire ASIO', 
         channel_map: 'Channel Mapping' = [1,2], 
         duration : 'Duration of recording' = 1, 
         out_file: 'Wavfile to save recording in' = 'out.wav'):
    dev = sd.query_devices(sound_device)
    sd.default.device = sd._get_device_id(sound_device, None)
    sd.default.samplerate = int(dev['default_samplerate'])
    print('Starting Recording')
    channel_map = [int(c) for c in channel_map]
    rec = sd.rec(duration * int(dev['default_samplerate']), mapping=channel_map)
    sd.wait()
    print('Silent samples', [rec.shape[0] - np.count_nonzero(rec[:,n]) for n in range(rec.shape[1])])
    wavfile.write(out_file, int(dev['default_samplerate']), rec)  
```

**Comment by mgeier** [comment] 2016-09-29 07:17
Hmmm, I don't know what's going on there ... 

Can you please print the return value of `sd.wait()`?

Can you please try some values for `blocksize` and see how that relates to the number of zeros you get?

**Comment by mathiassmichno** [comment] 2016-09-29 15:59
I modified the snippet slightly it is now:
```
import sounddevice as sd
from scipy.io import wavfile
import numpy as np
from pprint import pprint
import begin

@begin.start(auto_convert=True)
def main(sound_device: 'Sound Device Name' = 'DMX 6Fire ASIO', 
         channel_map: 'Channel Mapping' = [1,2], 
         duration : 'Duration of recording' = 1., 
         out_file: 'Wavfile to save recording in' = 'out.wav',
         blocksize: 'Block size (0 is optimal but may vary)' = 0,
         loops: 'Number of recordings in loop' = 1,
         format: 'dtype of recording' = 'float32'):
    dev = sd.query_devices(sound_device)
    pprint(dev)
    sd.default.device = sound_device
    sd.default.dtype = format
    sd.default.blocksize = blocksize
    print('Starting Recording')
    channel_map = [int(c) for c in channel_map]
    for i in range(loops):
        print('Loop #', i)
        rec = sd.rec(int(duration * dev['default_samplerate']), samplerate=int(dev['default_samplerate']), mapping=channel_map)
        print('  sd.wait() ->', sd.wait())
        for channel in range(rec.shape[1]):
            non_silence = np.where(rec[:,channel] > float(0))[0]
            print('  Ch. {}, initial silence {} samples'.format(channel, non_silence[0]))
        wavfile.write(str(i) + out_file, int(dev['default_samplerate']), rec)  
```

I tried to use a WASAPI device and recorded audio ten times in a loop.
It gave the following result (I also included the return of `sd.wait()`, but it is always `None`)
```
#: python audiorec.py -s "In 1 WASAPI" -b 1024 -l 10

{'default_high_input_latency': 0.01,
 'default_high_output_latency': 0.0,
 'default_low_input_latency': 0.003,
 'default_low_output_latency': 0.0,
 'default_samplerate': 48000.0,
 'hostapi': 3,
 'max_input_channels': 2,
 'max_output_channels': 0,
 'name': 'USBPAL In1 L/R (Terratec DMX 6fire WDM Audio)'}
Starting Recording
Loop # 0
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 1
  sd.wait() -> None
  Ch. 0, initial silence 447 samples
  Ch. 1, initial silence 477 samples
Loop # 2
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 3
  sd.wait() -> None
  Ch. 0, initial silence 0 samples
  Ch. 1, initial silence 1 samples
Loop # 4
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 5
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 6
  sd.wait() -> None
  Ch. 0, initial silence 265 samples
  Ch. 1, initial silence 256 samples
Loop # 7
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 8
  sd.wait() -> None
  Ch. 0, initial silence 256 samples
  Ch. 1, initial silence 256 samples
Loop # 9
  sd.wait() -> None
  Ch. 0, initial silence 257 samples
  Ch. 1, initial silence 268 samples
```
Changing the blocksize did not see to affect the Asio device; unless I set the blocksize to the same as the samples displayed under "Asio latency" in the driver software, which yields about half the initial silence as any other value.

**Comment by mgeier** [comment] 2016-09-29 16:49
I think your code `np.where(rec[:,channel] > float(0))[0][0]` doesn't yield the number of zeros but rather the number of non-positive values before the first positive value. Shouldn't it be rather something like `rec[:, channel].nonzero()[0][0]`?

> I also included the return of `sd.wait()`, but it is always `None`

OK, that's good, that means that there are no over/underflows.
You should probably only print this when its not `None`.

**Comment by mathiassmichno** [comment] 2016-09-29 16:54
I'm getting the same results, moreover I can confirm the silence when importing the out file in audacity and manually finding the first non zero sample.

However when I record om a MME device I am not getting any initial silence. Could it be an issue with PortAudio?

**Comment by mgeier** [comment] 2016-09-29 16:57
OK, if it doesn't happen in MME, it sure looks like a PortAudio issue.

**Comment by mgeier** [comment] 2016-09-29 17:01
You should probably ask there: http://www.portaudio.com/contacts.html

**Comment by hiccup7** [comment] 2016-11-23 15:02
@mathiassmichno - You could try libportaudio64bit.dll from the portaudio-19.6.0-win branch at https://github.com/spatialaudio/portaudio-binaries
portaudio has fixed a lot of bugs since revision 1899 bundled in the sounddevice 0.3.5 Windows wheel.

**Comment by hiccup7** [comment] 2016-11-23 23:03
Another option is to install the wheel with the updated PortAudio library from http://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice

**Comment by mathiassmichno** [comment] 2016-12-08 14:12
I  downloaded the wheel from [](http://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice)
And it fixed the problem, at least according to my small test script.

Thanks!

**Comment by mgeier** [comment] 2016-12-19 16:57
I've just made a new release.
Can you please check if the problem is fixed now?

**Comment by mathiassmichno** [comment] 2016-12-27 10:15
According to my small test, the problem is fixed, and the initial silence is gone.

**Comment by mgeier** [comment] 2017-01-15 16:22
OK, thanks!

**Closed by mgeier** 2017-01-15 16:22 UTC
Labels: bug
