### ISSUE TITLE
sounddevice blocks input()

### ISSUE THREAD

**Issue by sararob** [spatialaudio/python-sounddevice#61] opened 2016-12-29 16:30 UTC
sounddevice seems to block `input()` from printing text. Here's a simple repro:

```
import sounddevice as sd
name = input("Enter your name: ")
print ("your name is " + name)
```

When I comment out the first line it works as expected, but with the `sounddevice` import it doesn't print anything to the console. I've tried this:

```
import sys
sys.stdout.flush()
```

but that doesn't fix the issue. Anyone else having this problem or know how to fix it? I'm using Python 3.6.

**Comment by mgeier** [comment] 2016-12-30 10:24
This is quite strange, since the `input()` prompt is supposed to be shown on "standard output" instead of "standard error". I've asked about this at http://stackoverflow.com/q/41394554/.

**Comment by mgeier** [comment] 2016-12-30 11:11
Wow, this is surprisingly complicated!

It turns out that my stackoverflow question is a duplicate of http://stackoverflow.com/q/14009714/.

And the whole thing seems to be somewhat of a bug in Python, at least it's not quite clear what the desired behavior should be. This might or might not be changed in future Python version, there's an open issue: http://bugs.python.org/issue1927.

Since the current situation is so complicated, I don't really know what the proper solution for the `sounddevice` module should be.

Any suggestions?

For now, there is another work-around: just import the built-in `readline` module!

This should work as expected:

```python
import readline
import sounddevice as sd
name = input("Enter your name: ")
print ("your name is " + name)
```

The order of inports doesn't seem to matter.

**Comment by sararob** [comment] 2017-01-01 19:35
Thanks for investigating! That is indeed more complicated than I expected. The `readline` workaround fixes the issue for me, but if I have any thoughts on how to solve this for `sounddevice` I'll let you know.

**Comment by pdeboer1987** [comment] 2019-09-17 12:20
I may have a clue to this old issue.  Seems that an sd.InputStream will stop calling callback if you hit the enter key.  I will raise with code as another issue.

**Comment by mgeier** [comment] 2019-09-25 11:03
This is fixed in the newest release.

**Closed by mgeier** 2019-09-25 11:03 UTC
Labels: bug
